.github/workflows/ci-build.yml, modules/ghlint-reporting-sarif/src/main/kotlin/net/twisterrob/ghlint/reporting/SarifReporter.kt, modules/ghlint-snakeyaml/src/main/kotlin/net/twisterrob/ghlint/model/HasSnakeNode.kt, modules/ghlint-snakeyaml/src/main/kotlin/net/twisterrob/ghlint/model/SnakeJob.kt, modules/ghlint-snakeyaml/src/main/kotlin/net/twisterrob/ghlint/model/SnakeStep.kt, modules/ghlint-snakeyaml/src/main/kotlin/net/twisterrob/ghlint/model/SnakeWorkflow.kt, modules/ghlint-snakeyaml/src/main/kotlin/net/twisterrob/ghlint/yaml/Node.toLocation.kt, modules/ghlint-snakeyaml/src/main/kotlin/net/twisterrob/ghlint/yaml/NodeExtensions.kt
=> Fix #23: Target workflow/job/step more precisely + consistent number output

.github/workflows/ci-build.yml, gradle.properties, gradle/plugins/src/main/kotlin/net/twisterrob/ghlint/build/publishing.gradle.kts, gradle/plugins/src/main/kotlin/net/twisterrob/ghlint/net.twisterrob.ghlint.cli.gradle.kts, gradle/plugins/src/main/kotlin/net/twisterrob/ghlint/net.twisterrob.ghlint.library.gradle.kts, modules/ghlint-api/src/main/kotlin/net/twisterrob/ghlint/rule/Issue.kt, modules/ghlint-reporting-sarif/build.gradle, modules/ghlint-reporting-sarif/src/main/kotlin/net/twisterrob/ghlint/reporting/SarifReporter.kt, modules/ghlint-reporting-sarif/src/main/kotlin/net/twisterrob/ghlint/reporting/sarif/SarifReporter.kt, modules/ghlint/src/main/kotlin/net/twisterrob/ghlint/Main.kt
* Fixes #26: list non-compliant examples
* Fixes #21: generate all issues
* Add tool version to sarif
* Add level to sarif (this will trigger PR comments)
=> Sarif Reporting improvements

.github/workflows/ci-build.yml, config/detekt/detekt.yml, modules/ghlint-testing/src/main/kotlin/net/twisterrob/ghlint/testing/matcher.kt, modules/ghlint-testing/src/main/kotlin/net/twisterrob/ghlint/testing/testFinding.kt, modules/ghlint-testing/src/test/kotlin/net/twisterrob/ghlint/testing/MatcherKtTest.kt, modules/ghlint-testing/src/test/kotlin/net/twisterrob/ghlint/testing/TestRule.kt, modules/ghlint/build.gradle, modules/ghlint/src/main/kotlin/net/twisterrob/ghlint/Main.kt, modules/ghlint/src/main/kotlin/net/twisterrob/ghlint/reporting/GitHubCommandReporter.kt, modules/ghlint/src/test/kotlin/net/twisterrob/ghlint/reporting/GitHubCommandReporterTest.kt
Since the Sarif upload requires a paid permission in enterprise, this is a workaround to make it show on PRs. It only shows in "Files changed" and "Workflow run summary", but at least it's more visible than console logs.
=> GitHub Command reporter

modules/ghlint-api/src/main/kotlin/net/twisterrob/ghlint/analysis/SafeRule.kt, modules/ghlint-api/src/test/kotlin/net/twisterrob/ghlint/analysis/SafeRuleTest.kt, modules/ghlint-docs/build.gradle, modules/ghlint-docs/src/main/kotlin/net/twisterrob/ghlint/docs/MarkdownRenderer.kt, modules/ghlint-docs/src/test/kotlin/net/twisterrob/ghlint/docs/MarkdownRendererTest.kt, modules/ghlint-rules/src/main/kotlin/net/twisterrob/ghlint/rules/MissingJobTimeoutRule.kt
=> Fix #22: Render finding message on website, and swap code and explanation

modules/ghlint-rules/src/main/kotlin/net/twisterrob/ghlint/rules/DuplicateShellRule.kt, modules/ghlint-rules/src/main/kotlin/net/twisterrob/ghlint/rules/RedundantShellRule.kt, modules/ghlint-rules/src/test/kotlin/net/twisterrob/ghlint/rules/DuplicateShellRuleTest.kt, modules/ghlint-rules/src/test/kotlin/net/twisterrob/ghlint/rules/RedundantShellRuleTest.kt
=> Fix #57: DuplicateShell detects more duplications

modules/ghlint-rules/src/main/kotlin/net/twisterrob/ghlint/rules/DuplicateStepIdRule.kt, modules/ghlint-rules/src/main/kotlin/net/twisterrob/ghlint/rules/utils/editDistance.kt, modules/ghlint-rules/src/test/kotlin/net/twisterrob/ghlint/rules/DuplicateStepIdRuleTest.kt, modules/ghlint-rules/src/test/kotlin/net/twisterrob/ghlint/rules/utils/EditDistanceTest.kt
=> Fix #42: DuplicateStepIdRule with SimilarStepId issue

modules/ghlint-jsonschema/src/main/kotlin/net/twisterrob/ghlint/yaml/SnakeYamlJsonNode.kt, modules/ghlint-jsonschema/src/main/kotlin/net/twisterrob/ghlint/yaml/YamlValidation.kt
1500 tests ran in 8 seconds before, now it's sub 4 seconds.
=> YAML JSON Schema validation cleanup (~2x speedup)

modules/ghlint-api/src/main/kotlin/net/twisterrob/ghlint/model/Job.kt, modules/ghlint-rules/src/test/kotlin/net/twisterrob/ghlint/rules/MissingJobTimeoutRuleTest.kt, modules/ghlint-snakeyaml/src/main/kotlin/net/twisterrob/ghlint/model/SnakeJob.kt
=> Fix #107: timeout-minutes is not always a number

modules/ghlint-api/src/main/kotlin/net/twisterrob/ghlint/analysis/SafeRule.kt, modules/ghlint-api/src/test/kotlin/net/twisterrob/ghlint/analysis/SafeRuleTest.kt
=> Fix #60: Escape stack trace

.github/ISSUE_TEMPLATE/bug.yml, .github/release.yml
=> Fix #55: GitHub release categorization + issue template for bug

modules/ghlint-api/src/main/kotlin/net/twisterrob/ghlint/model/Job.kt, modules/ghlint-rules/src/main/kotlin/net/twisterrob/ghlint/rules/DefaultRuleSet.kt, modules/ghlint-rules/src/main/kotlin/net/twisterrob/ghlint/rules/ExplicitJobPermissionsRule.kt, modules/ghlint-rules/src/main/kotlin/net/twisterrob/ghlint/rules/MissingGhTokenRule.kt, modules/ghlint-rules/src/main/kotlin/net/twisterrob/ghlint/rules/PreferGitHubTokenRule.kt, modules/ghlint-rules/src/test/kotlin/net/twisterrob/ghlint/rules/PreferGitHubTokenRuleTest.kt, modules/ghlint-snakeyaml/src/main/kotlin/net/twisterrob/ghlint/model/SnakeJob.kt
=> Fix #91: PrefereGitHubToken rule

action.yml
* Fixes #132 
* Introduces #133
=> Fix #132: Handle spaces in file names in action

README.md, modules/ghlint-docs/src/main/kotlin/net/twisterrob/ghlint/docs/cli/main.kt, modules/ghlint-docs/src/main/resources/cli.md, website/docs/index.md
=> Fix #147: CLI docs

modules/ghlint-api/src/test/kotlin/net/twisterrob/ghlint/analysis/SafeRuleTest.kt, modules/ghlint-jsonschema/src/main/kotlin/net/twisterrob/ghlint/analysis/JsonSchemaValidationRule.kt, modules/ghlint-jsonschema/src/main/kotlin/net/twisterrob/ghlint/analysis/Validator.kt, modules/ghlint-jsonschema/src/test/kotlin/net/twisterrob/ghlint/analysis/JsonSchemaValidationRuleTest.kt, modules/ghlint-jsonschema/src/test/kotlin/net/twisterrob/ghlint/analysis/ValidatorTest.kt, modules/ghlint-snakeyaml/src/main/kotlin/net/twisterrob/ghlint/yaml/Node.toLocation.kt, modules/ghlint-testing/src/main/kotlin/net/twisterrob/ghlint/testing/jupiter/AcceptFailingDynamicTestExtension.kt, modules/ghlint-testing/src/main/kotlin/net/twisterrob/ghlint/testing/test.kt
=> Fix #131: handle errors coming from Yaml loading

modules/ghlint-rules/src/main/kotlin/net/twisterrob/ghlint/rules/FailFastActionsRule.kt, modules/ghlint-rules/src/test/kotlin/net/twisterrob/ghlint/rules/FailFastActionsRuleTest.kt
=> Fix #124: FailFastSoftpropsGhRelease: Implement softprops/action-gh-release check

modules/ghlint-rules/src/main/kotlin/net/twisterrob/ghlint/rules/DuplicateStepIdRule.kt, modules/ghlint-rules/src/test/kotlin/net/twisterrob/ghlint/rules/DuplicateStepIdRuleTest.kt
=> Fix #166: Make SimilarStepId more lenient

modules/ghlint-rules/src/main/kotlin/net/twisterrob/ghlint/rules/DuplicateStepIdRule.kt, modules/ghlint-rules/src/main/kotlin/net/twisterrob/ghlint/rules/utils/editDistance.kt, modules/ghlint-rules/src/test/kotlin/net/twisterrob/ghlint/rules/DuplicateStepIdRuleTest.kt, modules/ghlint-rules/src/test/kotlin/net/twisterrob/ghlint/rules/utils/EditDistanceTest.kt
* Fix #173
* Added some performance test
| Tests before | Tests after |
| - | - |
| ![image](https://github.com/TWiStErRob/net.twisterrob.ghlint/assets/2906988/4c048d8e-f6c0-49bb-a042-4db609fbb0de) | ![image](https://github.com/TWiStErRob/net.twisterrob.ghlint/assets/2906988/3ab9e85f-938f-4621-a4ab-796eee45c4b8) |
=> Fix #173: Reimplement editDistance with dynamic programming for performance

modules/ghlint-api/src/main/kotlin/net/twisterrob/ghlint/model/Action.kt, modules/ghlint-api/src/main/kotlin/net/twisterrob/ghlint/model/Component.kt, modules/ghlint-api/src/main/kotlin/net/twisterrob/ghlint/model/RawFile.kt, modules/ghlint-api/src/main/kotlin/net/twisterrob/ghlint/model/Workflow.kt, modules/ghlint-api/src/test/kotlin/net/twisterrob/ghlint/model/WorkflowTest.kt, modules/ghlint-docs/src/main/kotlin/net/twisterrob/ghlint/docs/issues/DocumentationRuleSet.kt, modules/ghlint-docs/src/main/kotlin/net/twisterrob/ghlint/docs/issues/MarkdownRenderer.kt, modules/ghlint-docs/src/main/kotlin/net/twisterrob/ghlint/docs/issues/main.kt, modules/ghlint-jsonschema/src/main/kotlin/net/twisterrob/ghlint/analysis/Validator.kt, modules/ghlint-jsonschema/src/main/kotlin/net/twisterrob/ghlint/yaml/YamlValidation.kt, modules/ghlint-jsonschema/src/test/kotlin/net/twisterrob/ghlint/analysis/ValidatorTest.kt, modules/ghlint-snakeyaml/src/main/kotlin/net/twisterrob/ghlint/model/SnakeAction.kt, modules/ghlint-snakeyaml/src/main/kotlin/net/twisterrob/ghlint/model/SnakeComponentFactory.kt, modules/ghlint-snakeyaml/src/main/kotlin/net/twisterrob/ghlint/model/SnakeWorkflow.kt, modules/ghlint-snakeyaml/src/main/kotlin/net/twisterrob/ghlint/yaml/Node.toLocation.kt, modules/ghlint-snakeyaml/src/main/kotlin/net/twisterrob/ghlint/yaml/SnakeYaml.kt, modules/ghlint-snakeyaml/src/test/kotlin/net/twisterrob/ghlint/model/WorkflowTest.kt, modules/ghlint-snakeyaml/src/test/kotlin/net/twisterrob/ghlint/yaml/NodeExtensionsTest.kt, modules/ghlint-snakeyaml/src/test/kotlin/net/twisterrob/ghlint/yaml/SnakeYamlTest.kt, modules/ghlint-testing/src/main/kotlin/net/twisterrob/ghlint/testing/check.kt, modules/ghlint-testing/src/main/kotlin/net/twisterrob/ghlint/testing/validate.kt, modules/ghlint/src/main/kotlin/net/twisterrob/ghlint/GHLint.kt
Extracted some renames from #44 to make it simpler to review.
=> Prepare for #44: Renames

README.md, action.yml, ghlint.bat, modules/ghlint-api/src/main/kotlin/net/twisterrob/ghlint/model/FileLocation.kt, modules/ghlint-docs/src/test/kotlin/net/twisterrob/ghlint/docs/issues/MarkdownRendererTest.kt, modules/ghlint/src/test/kotlin/net/twisterrob/ghlint/analysis/ValidationRuleTest.kt
This was mostly done in #44 this is just adding tests.
=> JSON-schema validation for actions

modules/ghlint-api/src/main/kotlin/net/twisterrob/ghlint/model/Job.kt, modules/ghlint-rules/src/main/kotlin/net/twisterrob/ghlint/rules/DefaultRuleSet.kt, modules/ghlint-rules/src/main/kotlin/net/twisterrob/ghlint/rules/JobDependenciesRule.kt, modules/ghlint-rules/src/test/kotlin/net/twisterrob/ghlint/rules/JobDependenciesRuleTest.kt, modules/ghlint-snakeyaml/src/main/kotlin/net/twisterrob/ghlint/model/SnakeJob.kt, modules/ghlint-snakeyaml/src/test/kotlin/net/twisterrob/ghlint/model/SnakeJobTest.kt
=> Fix #92/#207: JobDependenciesRule to detect invalid `Job.needs` reference and cycles (no starting job)

modules/ghlint-api/src/main/kotlin/net/twisterrob/ghlint/analysis/SafeRule.kt, modules/ghlint-api/src/test/kotlin/net/twisterrob/ghlint/analysis/SafeRuleTest.kt, modules/ghlint-docs/src/test/kotlin/net/twisterrob/ghlint/docs/issues/MarkdownRendererTest.kt
=> Fix #135: Error contains file name that failed the checking

modules/ghlint-rules/src/main/kotlin/net/twisterrob/ghlint/rules/ExplicitJobPermissionsRule.kt, modules/ghlint-rules/src/test/kotlin/net/twisterrob/ghlint/rules/ExplicitJobPermissionsRuleTest.kt
=> Fix #127/#128: MissingJobPermissions/ExplicitJobPermissions to support reusable workflow call jobs

README.md, website/.gitignore, website/build.gradle.kts, website/docs/index.md, website/docs/usage/gha.md, website/docs/usage/index.md
... and that implies simper README.md!
=> Full(er) usage documentation on website

.idea/codeStyles/Project.xml, .idea/codeStyles/codeStyleConfig.xml, .idea/inspectionProfiles/Project_Default.xml, README.md, action.yml, docs/RELEASING.md, gradle/plugins/src/main/kotlin/net/twisterrob/ghlint/build/dsl/LazyArgumentProvider.kt, modules/ghlint-api/src/main/kotlin/net/twisterrob/ghlint/Metadata.kt, modules/ghlint-api/src/main/kotlin/net/twisterrob/ghlint/model/ActionStep.kt, modules/ghlint-api/src/main/kotlin/net/twisterrob/ghlint/model/WorkflowStep.kt, modules/ghlint-api/src/test/kotlin/net/twisterrob/ghlint/model/InvalidContentTest.kt, modules/ghlint-api/src/test/kotlin/net/twisterrob/ghlint/results/LocationTest.kt, modules/ghlint-docs/build.gradle, modules/ghlint-docs/src/main/kotlin/net/twisterrob/ghlint/docs/issues/DocumentationRuleSet.kt, modules/ghlint-docs/src/test/kotlin/net/twisterrob/ghlint/docs/issues/MarkdownRendererTest.kt, modules/ghlint-reporting-sarif/src/main/kotlin/net/twisterrob/ghlint/reporting/sarif/ProguardWorkaround.kt, modules/ghlint-reporting-sarif/src/test/kotlin/net/twisterrob/ghlint/reporting/sarif/Issue_helpMarkdownTest.kt, modules/ghlint-reporting-sarif/src/test/resources/net/twisterrob/ghlint/reporting/sarif/report.sarif.json, modules/ghlint-rules/src/main/kotlin/net/twisterrob/ghlint/rules/DuplicateStepIdRule.kt, modules/ghlint-rules/src/main/kotlin/net/twisterrob/ghlint/rules/MissingShellRule.kt, modules/ghlint-rules/src/test/kotlin/net/twisterrob/ghlint/rules/JobDependenciesRuleTest.kt, modules/ghlint-snakeyaml/src/main/kotlin/net/twisterrob/ghlint/model/SnakeJob.kt, modules/ghlint-testing/src/main/kotlin/net/twisterrob/ghlint/testing/jupiter/AcceptFailingDynamicTestExtension.kt, modules/ghlint/src/main/kotlin/net/twisterrob/ghlint/reporting/TextReporter.kt, website/README.md, website/docs/rules/index.md, website/docs/usage/gha.md, website/docs/usage/index.md
* reformat whole codebase
* review inspection warnings
=> Share code style (formatting) and inspections (warnings) for IntelliJ IDEA

modules/ghlint-jsonschema/src/main/kotlin/net/twisterrob/ghlint/yaml/YamlValidation.kt, modules/ghlint-jsonschema/src/main/kotlin/net/twisterrob/ghlint/yaml/detectDuplicateKeys.kt, modules/ghlint-jsonschema/src/test/kotlin/net/twisterrob/ghlint/yaml/DetectDuplicateKeysKtTest.kt, modules/ghlint-jsonschema/src/test/kotlin/net/twisterrob/ghlint/yaml/YamlValidationTest.kt, modules/ghlint-jsonschema/src/test/kotlin/net/twisterrob/ghlint/yaml/matchers-Problem.kt, modules/ghlint-snakeyaml/src/main/kotlin/net/twisterrob/ghlint/yaml/Node.resolve.kt, modules/ghlint/src/test/kotlin/net/twisterrob/ghlint/analysis/ValidationRuleTest.kt
=> Fix #224: Implement duplicate key as "schema validation"

modules/ghlint-api/src/main/kotlin/net/twisterrob/ghlint/model/Env.kt, modules/ghlint-api/src/main/kotlin/net/twisterrob/ghlint/model/Job.kt, modules/ghlint-api/src/main/kotlin/net/twisterrob/ghlint/model/Step.kt, modules/ghlint-api/src/main/kotlin/net/twisterrob/ghlint/model/Workflow.kt, modules/ghlint-rules/src/main/kotlin/net/twisterrob/ghlint/rules/EmptyEnvRule.kt, modules/ghlint-rules/src/main/kotlin/net/twisterrob/ghlint/rules/MissingGhTokenRule.kt, modules/ghlint-rules/src/main/kotlin/net/twisterrob/ghlint/rules/PreferGitHubTokenRule.kt, modules/ghlint-rules/src/test/kotlin/net/twisterrob/ghlint/rules/EmptyEnvRuleTest.kt, modules/ghlint-rules/src/test/kotlin/net/twisterrob/ghlint/rules/MissingGhTokenRuleTest.kt, modules/ghlint-rules/src/test/kotlin/net/twisterrob/ghlint/rules/PreferGitHubTokenRuleTest.kt, modules/ghlint-snakeyaml/src/main/kotlin/net/twisterrob/ghlint/model/SnakeActionStep.kt, modules/ghlint-snakeyaml/src/main/kotlin/net/twisterrob/ghlint/model/SnakeComponentFactory.kt, modules/ghlint-snakeyaml/src/main/kotlin/net/twisterrob/ghlint/model/SnakeEnv.kt, modules/ghlint-snakeyaml/src/main/kotlin/net/twisterrob/ghlint/model/SnakeJob.kt, modules/ghlint-snakeyaml/src/main/kotlin/net/twisterrob/ghlint/model/SnakeWorkflow.kt, modules/ghlint-snakeyaml/src/main/kotlin/net/twisterrob/ghlint/model/SnakeWorkflowStep.kt
* Fixes #221 (specifically the crashes)
=> Fix #221: abstract .env into an interface with map/text

modules/ghlint-api/src/main/kotlin/net/twisterrob/ghlint/model/Action.kt, modules/ghlint-api/src/main/kotlin/net/twisterrob/ghlint/model/ActionStep.kt, modules/ghlint-api/src/main/kotlin/net/twisterrob/ghlint/model/Job.kt, modules/ghlint-api/src/main/kotlin/net/twisterrob/ghlint/model/Step.kt, modules/ghlint-api/src/main/kotlin/net/twisterrob/ghlint/model/WorkflowStep.kt, modules/ghlint-extensions/build.gradle, modules/ghlint-extensions/src/main/kotlin/net/twisterrob/ghlint/model/isCheckout.kt, modules/ghlint-extensions/src/main/kotlin/net/twisterrob/ghlint/model/seesEnvVar.kt, modules/ghlint-extensions/src/main/kotlin/net/twisterrob/ghlint/model/steps.kt, modules/ghlint-extensions/src/main/kotlin/net/twisterrob/ghlint/model/usesGhCli.kt, modules/ghlint-extensions/src/test/kotlin/net/twisterrob/ghlint/model/DefaultShellKtTest.kt, modules/ghlint-extensions/src/test/kotlin/net/twisterrob/ghlint/model/EffectiveShellKtTest.kt, modules/ghlint-extensions/src/test/kotlin/net/twisterrob/ghlint/model/IsCheckoutKtTest.kt, modules/ghlint-extensions/src/test/kotlin/net/twisterrob/ghlint/model/SeesEnvVarKtTest.kt, modules/ghlint-extensions/src/test/kotlin/net/twisterrob/ghlint/model/StepsKtTest.kt, modules/ghlint-extensions/src/test/kotlin/net/twisterrob/ghlint/model/firstStep.kt, modules/ghlint-rules/src/main/kotlin/net/twisterrob/ghlint/rules/DefaultRuleSet.kt, modules/ghlint-rules/src/main/kotlin/net/twisterrob/ghlint/rules/MissingGhRepoRule.kt, modules/ghlint-rules/src/main/kotlin/net/twisterrob/ghlint/rules/MissingGhTokenRule.kt, modules/ghlint-rules/src/test/kotlin/net/twisterrob/ghlint/rules/MissingGhRepoRuleTest.kt, modules/ghlint-rules/src/test/kotlin/net/twisterrob/ghlint/rules/MissingGhTokenRuleTest.kt, modules/ghlint-snakeyaml/src/main/kotlin/net/twisterrob/ghlint/model/SnakeJob.kt, modules/ghlint-snakeyaml/src/main/kotlin/net/twisterrob/ghlint/model/SnakeRuns.kt, modules/ghlint-testing/src/main/kotlin/net/twisterrob/ghlint/testing/check.kt, modules/ghlint-testing/src/main/kotlin/net/twisterrob/ghlint/testing/load.kt, modules/ghlint-testing/src/main/kotlin/net/twisterrob/ghlint/testing/validate.kt
=> Fix #247: Implement MissingGhRepoRule

modules/ghlint-rules/src/main/kotlin/net/twisterrob/ghlint/rules/ExplicitJobPermissionsRule.kt
=> Fix broken tests in #282: Move example to the other issue

.github/workflows/ci-publish.yml
=> Add a workflow_run trigger on main in preparation for fixing #286

modules/ghlint-api/src/main/kotlin/net/twisterrob/ghlint/model/Job.kt, modules/ghlint-api/src/main/kotlin/net/twisterrob/ghlint/model/Permission.kt, modules/ghlint-api/src/main/kotlin/net/twisterrob/ghlint/model/Permissions.kt, modules/ghlint-api/src/main/kotlin/net/twisterrob/ghlint/model/Workflow.kt, modules/ghlint-api/src/test/kotlin/net/twisterrob/ghlint/model/AccessTest.kt, modules/ghlint-api/src/test/kotlin/net/twisterrob/ghlint/model/PermissionTest.kt, modules/ghlint-api/src/test/kotlin/net/twisterrob/ghlint/model/PermissionsTest.kt, modules/ghlint-api/src/test/kotlin/net/twisterrob/ghlint/model/ScopeTest.kt, modules/ghlint-snakeyaml/src/main/kotlin/net/twisterrob/ghlint/model/SnakeComponentFactory.kt, modules/ghlint-snakeyaml/src/main/kotlin/net/twisterrob/ghlint/model/SnakeJob.kt, modules/ghlint-snakeyaml/src/main/kotlin/net/twisterrob/ghlint/model/SnakePermissions.kt, modules/ghlint-snakeyaml/src/main/kotlin/net/twisterrob/ghlint/model/SnakeWorkflow.kt, modules/ghlint-snakeyaml/src/test/kotlin/net/twisterrob/ghlint/model/SnakePermissionsTest.kt
As discussed on #294 - breaking down the pull request to be more sensible in scope.
This PR brings across the Permissions model.
=> Add Permission/Permissions model

modules/ghlint-api/src/main/kotlin/net/twisterrob/ghlint/ruleset/LazyRuleSet.kt, modules/ghlint-api/src/main/kotlin/net/twisterrob/ghlint/ruleset/ReflectiveRuleSet.kt, modules/ghlint-docs/src/test/kotlin/net/twisterrob/ghlint/docs/issues/MarkdownRendererTest.kt, modules/ghlint-reporting-sarif/src/test/kotlin/net/twisterrob/ghlint/reporting/sarif/SarifReporterTest.kt, modules/ghlint-rules/src/main/kotlin/net/twisterrob/ghlint/rules/DefaultRuleSet.kt, modules/ghlint/src/main/kotlin/net/twisterrob/ghlint/BuiltInRuleSet.kt
I ran it a few times and reflection was around 1.69, while lazy was 1.58, so it seems to worth it.
=> Use default constructors directly to speed up instantiation

.github/workflows/usage.yml, website/docs/usage/gha.md
=> Fix #274: Make example more copy-paste-able
